spring:
  application:
    name: webshopping

  datasource:
    url: jdbc:mysql://localhost:3306/project2
    username: master
    password: password
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: admin
      password: 1234