spring:
  application:
    name: webshopping
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/project2
    username: master
    password: password
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  security:
    user:
      name: admin
      password: 1234

  cloud:
    aws:
      s3:
        bucket: elice5-project2-bucket
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2

